Repository RGB-WG/rgb-core, pull requests merged in 2021-03, with the labels that each got.

#23 Implementation of Revealed Merge operation.
  src/contract/assignments.rs
  src/contract/mod.rs
  src/contract/nodes.rs
  src/contract/reveal.rs
  src/lib.rs
  src/schema/nodes.rs
  src/validation.rs
Labels: bug, enhancement

#26 Disclosure implementation: closes #13
  Cargo.lock
  Cargo.toml
  src/bech32.rs
  src/contract/nodes.rs
  src/contract/reveal.rs
  src/lib.rs
  src/stash/anchor.rs
  src/stash/consignment.rs
  src/stash/disclosure.rs
  src/stash/mod.rs
  src/stash/stash.rs
Labels: epic

#66 Fix mac installation command
  README.md
Labels: documentation

#65 TODO Items annotated with referencing Issue number
  codecov.yml
  rgb20/src/asset.rs
  rgb20/src/schema.rs
  rgb20/src/supply.rs
  rgb21/src/schema.rs
  rgb22/src/schema.rs
  rgb23/src/schema.rs
  rgb24/src/schema.rs
  src/bech32.rs
  src/contract/data.rs
  src/contract/metadata.rs
  src/contract/nodes.rs
  src/schema/mod.rs
  src/schema/schema.rs
  src/schema/state.rs
  src/schema/types.rs
  src/stash/anchor.rs
  src/stash/consignment.rs
  src/stash/disclosure.rs
  src/validation.rs
  src/vm/embedded.rs
Labels: documentation

#71 Refactoring scripts
  rgb20/src/schema.rs
  rgb20/src/transitions.rs
  rgb21/src/schema.rs
  rgb22/src/schema.rs
  rgb23/src/schema.rs
  rgb24/src/schema.rs
  src/bech32.rs
  src/contract/nodes.rs
  src/lib.rs
  src/schema/mod.rs
  src/schema/nodes.rs
  src/schema/schema.rs
  src/schema/script.rs
  src/schema/state.rs
  src/stash/anchor.rs
  src/validation.rs
  src/vm/embedded.rs
  test/genesis.in
  test/transition.in
Labels: [CONSENSUS-CRITICAL], epic, refactoring

#67 TODO annotation updated after removing duplication
  rgb21/src/schema.rs
  rgb22/src/schema.rs
  rgb23/src/schema.rs
  src/contract/data.rs
  src/schema/state.rs
  src/schema/types.rs
  src/vm/embedded.rs
Labels: documentation
