Repository RGB-WG/rgb-core, pull requests merged in 2021-02, with the labels that each got.

#2 Fixes 127: duplicated outputs
  src/stash/anchor.rs
Labels: bug

#3 Fix for pull request #2
  src/stash/anchor.rs
Labels: bug

#8 Fixing node_id mutability issue by incomplete concealements
  Cargo.lock
  Cargo.toml
  src/bech32.rs
  src/contract/assignments.rs
  src/contract/conceal.rs
  src/contract/data.rs
  src/contract/metadata.rs
  src/contract/mod.rs
  src/contract/nodes.rs
  src/contract/seal.rs
  src/contract/value.rs
  src/lib.rs
  src/schema/schema.rs
  src/schema/state.rs
  src/validation.rs
  src/vm/embedded.rs
Labels: bug

#5 Modification of Stash trait
  src/stash/stash.rs
Labels: enhancement

#21 Fix commit encoding tests
  Cargo.lock
  src/bech32.rs
  src/contract/assignments.rs
  src/contract/metadata.rs
  src/contract/nodes.rs
  src/stash/stash.rs
  test/declarative_state.in
  test/hash_state.in
  test/metadata.in
  test/parent_rights.in
  test/pedersan_state.in
Labels: tests

#22 Consignment concealment
  src/stash/anchor.rs
  src/stash/consignment.rs
  src/stash/stash.rs
Labels: enhancement
