Repository RGB-WG/rgb-core, pull requests merged in 2021-04, with the labels that each got.

#82 Virtual machine & dynamic verification rewrite.
  Cargo.lock
  Cargo.toml
  rgb20/src/schema.rs
  rgb21/src/schema.rs
  rgb22/src/schema.rs
  src/bin/rgb.rs
  src/contract/assignments.rs
  src/contract/mod.rs
  src/contract/nodes.rs
  src/contract/reveal.rs
  src/lib.rs
  src/schema/mod.rs
  src/schema/nodes.rs
  src/schema/schema.rs
  src/schema/script.rs
  src/schema/state.rs
  src/stash/consignment.rs
  src/validation.rs
  src/vm/embedded.rs
  src/vm/mod.rs
  src/vm/simplicity.rs
  src/vm/vm.rs
Labels: [CONSENSUS-CRITICAL], epic, refactoring

#76 contrib/test.sh updated
  contrib/depCargo.toml
  contrib/test.sh
Labels: ci

#80 known inflation transformed into method
  rgb20/src/asset.rs
Labels: enhancement
