Repository RGB-WG/rgb-core, pull requests merged in 2024-03, with the labels that each got.

#201 Improvement RGB Isa instructions
  src/contract/operations.rs
  src/stl.rs
  src/vm/macroasm.rs
  src/vm/op_contract.rs
  stl/AnchoredBundle.vesper
  stl/RGB@0.1.0.sta
  stl/RGB@0.1.0.stl
  stl/RGB@0.1.0.sty
  stl/Transition.vesper
Labels: bug, *consensus*, *security*

#211 Contract: add timestamp and issuer to genesis
  src/contract/commit.rs
  src/contract/mod.rs
  src/contract/operations.rs
  src/stl.rs
  stl/RGB@0.1.0.sta
  stl/RGB@0.1.0.stl
  stl/RGB@0.1.0.sty
  stl/Transition.vesper
Labels: *consensus*, *security*, feature

#213 Reserve space for future features and inter-contract protocols
  src/contract/assignments.rs
  src/contract/commit.rs
  src/contract/operations.rs
  src/lib.rs
  src/schema/schema.rs
  src/schema/script.rs
  src/stl.rs
  stl/AnchoredBundle.vesper
  stl/RGB@0.1.0.sta
  stl/RGB@0.1.0.stl
  stl/RGB@0.1.0.sty
  stl/Schema.vesper
  stl/Transition.vesper
Labels: *consensus*

#216 Fix serde text serializations
  src/contract/anchor.rs
  src/contract/assignments.rs
  src/contract/contract.rs
  src/contract/data.rs
  src/contract/fungible.rs
  src/contract/operations.rs
  src/contract/seal.rs
  src/contract/state.rs
  src/contract/xchain.rs
  src/schema/mod.rs
  src/schema/schema.rs
  src/schema/script.rs
  src/schema/state.rs
  src/stl.rs
  src/validation/logic.rs
  src/validation/schema.rs
  src/validation/validator.rs
  src/vm/mod.rs
  src/vm/script.rs
Labels: enhancement

#218 Return u8 error code instead of string from VM
  src/validation/status.rs
  src/vm/runtime.rs
Labels: enhancement

#220 Use new ASCII armoring technique
  Cargo.lock
  Cargo.toml
  src/schema/schema.rs
  src/schema/script.rs
  src/stl.rs
  src/vm/script.rs
  stl/RGB@0.1.0.sta
  stl/RGB@0.1.0.stl
  stl/RGB@0.1.0.sty
  stl/Schema.vesper
Labels: tests, refactoring

#222 Move ReservedBytes to commit_verify crate
  Cargo.lock
  Cargo.toml
  src/contract/assignments.rs
  src/contract/commit.rs
  src/contract/operations.rs
  src/lib.rs
  src/schema/schema.rs
  src/stl.rs
  stl/AnchoredBundle.vesper
  stl/RGB@0.1.0.sta
  stl/RGB@0.1.0.stl
  stl/RGB@0.1.0.sty
  stl/Schema.vesper
  stl/Transition.vesper
Labels: *compatibility*

#223 Support extensibility in the set of Layers 1
  Cargo.lock
  Cargo.toml
  src/contract/anchor.rs
  src/contract/seal.rs
  src/contract/xchain.rs
Labels: *compatibility*, *consensus*
